name: CMake

on: push

env:
  BUILD_TYPE: Release

jobs:
  testing:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        llvm_version: [10, 11]

    steps:
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.16.x'    
    
    - name: Install GTest
      run: |
        sudo apt-get install libgtest-dev
        cd /usr/src/gtest 
        sudo cmake CMakeLists.txt -Dgtest_disable_pthreads=ON
        sudo make 
        sudo make install

    - name: Install LLVM ${{ matrix.llvm_version }}
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{ matrix.llvm_version }}
        sudo apt-get -y install zlib1g-dev
     
    - uses: actions/checkout@v2
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DTESTS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j2

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Test Installed
      run: |
        cd ${{github.workspace}}/build
        sudo make install
        cd ${{github.workspace}}/tests/install_test
        mkdir build && cd build
        cmake ..
        make
        ./install_test
      
  format:
    runs-on: ubuntu-18.04
    env: 
      CLANG_FORMAT_VERSION: 10
    steps:
    - name: Install Clang Format ${{env.CLANG_FORMAT_VERSION}}
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{env.CLANG_FORMAT_VERSION}}
        sudo apt-get remove clang-format*
        sudo apt-get -y install clang-format-${{env.CLANG_FORMAT_VERSION}} zlib1g-dev
        sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-${{env.CLANG_FORMAT_VERSION}} 10
    
    - name: Show Clang Format Version
      run: clang-format --version

    - uses: actions/checkout@v2

    - name: Check Formating
      run: |
        ./.dev/format.sh $(which clang-format) .
        git diff > formatting.patch
        cat formatting.patch 
        if [ -s ./formatting.patch ]; then (exit 166); fi
